// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx3Jty_yaG3ZRMWQJLgHhGfP8QuOwriGc',
    appId: '1:372365108449:web:fb250fc2c34714792f83a0',
    messagingSenderId: '372365108449',
    projectId: 'doom-scroll-1f',
    authDomain: 'doom-scroll-1f.firebaseapp.com',
    storageBucket: 'doom-scroll-1f.firebasestorage.app',
    measurementId: 'G-1MP1EN53P1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHPnEOdtSCC7cECaiyPSzk03qMHqud_Oc',
    appId: '1:372365108449:android:c0f6466d459b6dd22f83a0',
    messagingSenderId: '372365108449',
    projectId: 'doom-scroll-1f',
    storageBucket: 'doom-scroll-1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASj3oEK27uwldXrFIxP6tdKr-eVwNuTbs',
    appId: '1:372365108449:ios:e512e4ac8c64b4e02f83a0',
    messagingSenderId: '372365108449',
    projectId: 'doom-scroll-1f',
    storageBucket: 'doom-scroll-1f.firebasestorage.app',
    iosBundleId: 'com.example.doomScroll',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx3Jty_yaG3ZRMWQJLgHhGfP8QuOwriGc',
    appId: '1:372365108449:web:f9f92037f417bbc42f83a0',
    messagingSenderId: '372365108449',
    projectId: 'doom-scroll-1f',
    authDomain: 'doom-scroll-1f.firebaseapp.com',
    storageBucket: 'doom-scroll-1f.firebasestorage.app',
    measurementId: 'G-J7KXR3ND3X',
  );
}
